-- Identifica e ordena os melhores
SELECT papel, SUM(score) AS score, (
	SELECT AVG(DB.volume_total_1) FROM dados_bayes DB WHERE DB.papel = S.papel AND data > '2021-12-31'
) AS volume FROM (
	SELECT papel_1 AS papel, (COUNT(*) * 10) AS score FROM simulacao_top_10 GROUP BY papel_1
	UNION ALL
	SELECT papel_2 AS papel, (COUNT(*) * 9) AS score FROM simulacao_top_10 GROUP BY papel_2
	UNION ALL
	SELECT papel_3 AS papel, (COUNT(*) * 8) AS score FROM simulacao_top_10 GROUP BY papel_3
	UNION ALL
	SELECT papel_4 AS papel, (COUNT(*) * 7) AS score FROM simulacao_top_10 GROUP BY papel_4
	UNION ALL
	SELECT papel_5 AS papel, (COUNT(*) * 6) AS score FROM simulacao_top_10 GROUP BY papel_5
	UNION ALL
	SELECT papel_6 AS papel, (COUNT(*) * 5) AS score FROM simulacao_top_10 GROUP BY papel_6
	UNION ALL
	SELECT papel_7 AS papel, (COUNT(*) * 4) AS score FROM simulacao_top_10 GROUP BY papel_7
	UNION ALL
	SELECT papel_8 AS papel, (COUNT(*) * 3) AS score FROM simulacao_top_10 GROUP BY papel_8
	UNION ALL
	SELECT papel_9 AS papel, (COUNT(*) * 2) AS score FROM simulacao_top_10 GROUP BY papel_9
	UNION ALL
	SELECT papel_10 AS papel, (COUNT(*) * 1) AS score FROM simulacao_top_10 GROUP BY papel_10
) S
GROUP BY papel
ORDER BY score DESC, volume DESC;

-- Identifica os piores
WITH cte AS (
	SELECT papel, SUM(score) AS score, (
		SELECT AVG(DB.volume_total_1) FROM dados_bayes DB WHERE DB.papel = S.papel AND data > '2021-12-31'
	) AS volume FROM (
		SELECT papel_1 AS papel, (COUNT(*) * 10) AS score FROM simulacao_top_10 GROUP BY papel_1
		UNION ALL
		SELECT papel_2 AS papel, (COUNT(*) * 9) AS score FROM simulacao_top_10 GROUP BY papel_2
		UNION ALL
		SELECT papel_3 AS papel, (COUNT(*) * 8) AS score FROM simulacao_top_10 GROUP BY papel_3
		UNION ALL
		SELECT papel_4 AS papel, (COUNT(*) * 7) AS score FROM simulacao_top_10 GROUP BY papel_4
		UNION ALL
		SELECT papel_5 AS papel, (COUNT(*) * 6) AS score FROM simulacao_top_10 GROUP BY papel_5
		UNION ALL
		SELECT papel_6 AS papel, (COUNT(*) * 5) AS score FROM simulacao_top_10 GROUP BY papel_6
		UNION ALL
		SELECT papel_7 AS papel, (COUNT(*) * 4) AS score FROM simulacao_top_10 GROUP BY papel_7
		UNION ALL
		SELECT papel_8 AS papel, (COUNT(*) * 3) AS score FROM simulacao_top_10 GROUP BY papel_8
		UNION ALL
		SELECT papel_9 AS papel, (COUNT(*) * 2) AS score FROM simulacao_top_10 GROUP BY papel_9
		UNION ALL
		SELECT papel_10 AS papel, (COUNT(*) * 1) AS score FROM simulacao_top_10 GROUP BY papel_10
	) S
	GROUP BY papel
)
SELECT DISTINCT papel
FROM dados_bayes
WHERE data >= '2022-06-01'
	AND papel NOT IN (SELECT papel FROM cte);

-- Ordena os piores
SELECT papel, AVG(DB.volume_total_1) AS volume
FROM dados_bayes DB
WHERE data > '2021-12-31'
	AND papel IN (
		'LLIS3F',
		'CTSA4',
		'BRGE11',
		'MTSA4F',
		'VINO11',
		'EUCA4F',
		'BRPR3F',
		'FLRY3F',
		'ATMP3F',
		'BPAN12F',
		'TELB3',
		'RBRP11',
		'IRDM11',
		'ECOR3',
		'BAZA3F',
		'BMIN4F',
		'MERC4',
		'CSRN3',
		'CVBI11',
		'PETZ3',
		'OSXB3',
		'VBBR3',
		'TASA4F',
		'QUAL3F',
		'TELB4',
		'CTNM3F',
		'SAPR4F',
		'DESK3F',
		'EUCA3F',
		'RECR11',
		'HBOR3F',
		'BRSR6',
		'VITT3',
		'RSID3F',
		'CRPT11',
		'IRBR3F',
		'BGIP4F',
		'VITT3F',
		'PINE4F',
		'FESA4F',
		'KINP11',
		'RANI3F',
		'HBRE3F',
		'DXCO3F',
		'CMIG3F',
		'TFCO4',
		'BRSR5F',
		'CVCB3',
		'SIMH3F',
		'UNIP5',
		'CRPG5F',
		'EURP11',
		'HBRE3',
		'CTSA4F',
		'UNIP3F',
		'ROMI3F',
		'TPIS3F',
		'ELET3F',
		'SCPF11',
		'GOLL11F',
		'AGXY3',
		'MEAL3F',
		'CEBR3F',
		'BRIV4F',
		'MATV11',
		'SRVD11',
		'PLPL3F',
		'SEQL3F',
		'LATR11B',
		'TASA3F',
		'CAML3',
		'LVTC3',
		'FESA3',
		'RECX11',
		'SMFT3F',
		'MCHF11',
		'OPCT3F',
		'PEMA11',
		'SEER3',
		'BRGE5',
		'TXRX3F',
		'JOPA4',
		'AMBP3F',
		'MODL3F',
		'VULC3F',
		'BRGE3F',
		'EALT4F',
		'FIVN11',
		'CSRN5F',
		'LIGT3F',
		'MRVE3F',
		'PTNT4F',
		'FESA3F',
		'AVLL3F',
		'MWET4F',
		'EKTR4F',
		'CBAV3',
		'VIVA3',
		'EPAR3F',
		'SGPS3F',
		'KRSA3F',
		'GGRC11',
		'REVE11',
		'USIM3F',
		'DMMO3',
		'GEPA4F',
		'TIMS3F',
		'ANIM3',
		'VVEO3F',
		'MILS3F',
		'AGXY3F',
		'ELMD3F',
		'BOAS3F',
		'BOVX11',
		'ITSA3F',
		'IFCM3F',
		'PARD3',
		'VLID3',
		'ENJU3',
		'RBRS11',
		'PRNR3F',
		'RAPT3F',
		'LAND3F',
		'ENEV3',
		'ALUP4F',
		'BRSR3F',
		'HBTS5F',
		'BRCO11',
		'HBSA3F',
		'SOMA3F',
		'PATI3F',
		'TECN3F',
		'BRGE8F',
		'ALPA4F',
		'BALM3F',
		'DTCY3F',
		'RCSL4',
		'DNAI11',
		'SULA3F',
		'GOAU3F',
		'VAMO3',
		'BPAC11',
		'GPAR3F',
		'BRFS3',
		'GOLD11',
		'MDNE3F',
		'BMEB3F',
		'UNIP5F',
		'GGPS3F',
		'CSRN6F',
		'WHRL4F',
		'BNBR3',
		'HAGA3F',
		'CSAB3F',
		'BRGE3',
		'NEWU11',
		'ALPA3F',
		'BPRP11',
		'JSLG3F',
		'AMAR3',
		'PABY11',
		'AZEV4F',
		'FSRF11F',
		'CGRA3F',
		'CSED3',
		'RNEW3F',
		'BAUH4F',
		'PGMN3',
		'RPAD3F',
		'ALPK3F',
		'BMEB4F',
		'CRDE3F',
		'NORD3F',
		'ESPA3F',
		'MATB11',
		'RPAD5F',
		'SULA11F',
		'SBFG3F',
		'BRSR6F',
		'BREV11',
		'IGBR3F',
		'VLID3F',
		'OURE11',
		'ENEV3F',
		'SMFT3',
		'EQPA3F',
		'BALM4',
		'MOVI3F',
		'BRIT3F',
		'MLAS3',
		'BRGE11F',
		'BRSR3',
		'TIMS3',
		'LWSA3F',
		'CASH3F',
		'BDLL4F',
		'CEGR3F',
		'SPXB11',
		'SHOT11',
		'FRAS3F',
		'MEGA3F',
		'CPLE5',
		'DRIT11B',
		'HCST11',
		'MTRE3F',
		'WHGR11',
		'SAPR3F',
		'FDES11F',
		'WLMM3F',
		'BALM4F',
		'FIQE3F',
		'BPAC11F',
		'IGTI11',
		'PFRM3F',
		'IDFI11',
		'FOOD11',
		'REDE3F',
		'BSLI4F',
		'ANIM3F',
		'CRPG6F',
		'PMAM3F',
		'FRTA3F',
		'RNEW4F',
		'CBAV3F',
		'CRIV4F',
		'EQPA5F',
		'VSLH11',
		'B3SA3F',
		'LAVV3F',
		'DOHL3F',
		'SNSY5F',
		'CEED3F',
		'SNSY3F',
		'TEKA4F',
		'JALL3F',
		'CALI3',
		'EALT3',
		'PORT3F',
		'CALI3F',
		'ITIP11',
		'DEXP4F',
		'MRFG3F',
		'EQPA3',
		'BRGE12F',
		'TEND3',
		'VOTS11',
		'MGLG11',
		'CXSE3F',
		'MEGA3',
		'RECV3F',
		'ABCB4F',
		'BOVB11',
		'BOBR4F',
		'CLSC3F',
		'RCSL3F',
		'MELK3F',
		'SNSY3',
		'ATOM3F',
		'SEER3F',
		'JFEN3F',
		'AZUL4F',
		'LUPA3F',
		'URPR11',
		'LJQQ3F',
		'HCHG11',
		'DIRR3F',
		'RNEW11F',
		'RECV3',
		'ARML3F',
		'IGTI3',
		'FRIO3F',
		'RAPT4F',
		'CSAB4F',
		'RDNI3F',
		'EZTC3F',
		'MGEL4F',
		'CAMB3F',
		'VCRR11',
		'EALT3F',
		'RPMG3F',
		'WEST3F',
		'BRAP3F',
		'EPAR3',
		'ONCO3F',
		'LJQQ3',
		'SNCI11',
		'CPLE5F',
		'CEED3',
		'HABT11',
		'CEDO3F',
		'CPLE6F',
		'WIZS3F',
		'BMIN3F',
		'CGRA4F',
		'RCSL4F',
		'MFAI11',
		'CPLE3F',
		'CACR11',
		'LPSB3F',
		'CSRN3F',
		'WLMM4',
		'JHSF3F',
		'RSUL4F',
		'ALUP3F',
		'LOGG3F',
		'CURY3F',
		'DXCO3',
		'KLBN3F',
		'PEAB4F',
		'KEPL3F',
		'MLAS3F',
		'SHUL4F',
		'POMO3F',
		'KLBN11F',
		'EQMA3BF',
		'GRND3F',
		'GETT3F',
		'ORVR3F',
		'PCAR3F',
		'GSHP3F',
		'CIEL3',
		'BTEK11',
		'HAAA11',
		'ETHE11',
		'PLAS3F',
		'GETT4F',
		'CEDO3',
		'MAPT3F',
		'KEPL3',
		'JOPA4F',
		'CLSA3F',
		'TXRX4F',
		'PDTC3F',
		'GGBR3F',
		'MODL3',
		'KLBN4F',
		'FSPE11F',
		'ARZZ3F',
		'INTB3F',
		'USIM6F',
		'CPLE11',
		'CRPG5',
		'HETA4F',
		'SMTO3',
		'NINJ3F',
		'DMMO3F',
		'RSUL4',
		'CRPG3F',
		'BNBR3F',
		'PEAB3F',
		'BRFS3F',
		'IGTI11F',
		'IGTI3F',
		'DMMO11F',
		'BMGB4F',
		'PTNT3F',
		'ARML3',
		'DEXP4',
		'META11',
		'MILL11',
		'BIOM3F',
		'CASH3',
		'AVLL3',
		'DMVF3',
		'TFCO4F',
		'TGMA3F',
		'ENGI4F',
		'PSVM11F',
		'CMDB11',
		'JOPA3F',
		'PDGR3F',
		'BAHI3F',
		'CTSA3F',
		'SULA4F',
		'TRIS3F',
		'CGAS3F',
		'TAEE4F',
		'SIMH3',
		'CEDO4F',
		'DVFF11',
		'MATD3F',
		'TEND3F',
		'SOND6F',
		'LVTC3F',
		'SHOW3F',
		'HAPV3',
		'AGRO3F',
		'POMO4F',
		'BRKM6F',
		'FSTU11F',
		'CBEE3F',
		'HRDF11',
		'DOHL4F',
		'WHRL3F',
		'MNDL3F',
		'STBP3',
		'SULA3',
		'TTEN3F',
		'LOGN3F',
		'BPAC5F',
		'PGMN3F',
		'RPAD6F',
		'BDLL3F',
		'PNVL3F',
		'ESTR4F',
		'TRPL3F',
		'OSXB3F',
		'CTNM4F',
		'CSED3F',
		'MERC4F',
		'CPTS11',
		'SLED11F',
		'VSEC11',
		'TRAD3F',
		'QAMI11',
		'RRRP3F',
		'MNPR3F',
		'CEEB3F',
		'INEP3F',
		'CRPG6',
		'EMAE4F',
		'DAMT11B',
		'AALR3F',
		'AZEV3F',
		'CLSC4F',
		'OFSA3F',
		'UCAS3F',
		'AESB3F',
		'SLED3F',
		'CRIV3F',
		'GENB11',
		'CTKA4F',
		'EEEL3F',
		'WLMM3',
		'BPAC5',
		'MOVI3',
		'LOGG3',
		'ENGI3F',
		'MBLY3F',
		'PTNT3',
		'PTBL3F',
		'VIVR3F',
		'FHER3',
		'BRIV3F',
		'NVHO11',
		'CEBR6F',
		'WLMM4F',
		'BRML3F',
		'HAGA4F',
		'HOSI11',
		'AMBP3',
		'BEES4F',
		'SYNE3',
		'BICR11',
		'GETT11F'
	)
GROUP BY papel
ORDER BY volume DESC;

-- Por fim junte a lista de papéis colocando os melhores ordenados primeiro e os piores ordenados por último
